services:
  - type: web
    name: wishport-backend
    env: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    branch: master
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: wishport-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: wishport-db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: wishport-db
          property: password
      - key: WISHPORT_JWT_SECRET
        generateValue: true

databases:
  - name: wishport-db
    databaseName: wishport_db
    user: wishport_user
