spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/wishport_db?createDatabaseIfNotExist=true&serverTimezone=Europe/Madrid&sslMode=REQUIRED}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:tu_password_aqui}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

wishport.jwt.secret=${JWT_SECRET:mi_clave_secreta_muy_larga_y_segura_para_firmar_tokens_jwt_debe_tener_al_menos_256_bits}

logging.level.com.wishport.backend=INFO
logging.level.org.springframework.security=WARN